apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: simple-reverse-proxy
  name: simple-reverse-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-reverse-proxy
  template:
    metadata:
      labels:
        app: simple-reverse-proxy
        service: reverse-proxy
    spec:
      containers:
      - image: kesar09/simple-reverse-proxy
        name: simple-reverse-proxy
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"       
        ports:
        - containerPort: 8080
      restartPolicy: Always


